import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar principal de Vibra Wiki.
 * Estructura manual con categorías organizadas por aplicación y tema.
 */

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // ── Introducción ──
    'intro',

    // ── Acerca de ──
    {
      type: 'category',
      label: 'Acerca de',
      items: ['about/about'],
    },

    // ── Aplicaciones ──
    {
      type: 'category',
      label: 'Aplicaciones',
      items: [
        {
          type: 'category',
          label: 'Vibra API (Backend)',
          items: [
            'applications/vibra-api/arquitectura',
            {
              type: 'category',
              label: 'Módulos',
              items: [
                'applications/vibra-api/modulos/actividades',
                'applications/vibra-api/modulos/emociones',
                'applications/vibra-api/modulos/auth',
                'applications/vibra-api/modulos/feedback',
                'applications/vibra-api/modulos/cursos',
                'applications/vibra-api/modulos/participantes',
                'applications/vibra-api/modulos/ranking',
                'applications/vibra-api/modulos/pretests',
                'applications/vibra-api/modulos/notificaciones',
              ],
            },
            'applications/vibra-api/endpoints',
          ],
        },
        {
          type: 'category',
          label: 'Vibra Web (Dashboard)',
          items: [
            'applications/vibra-web/dashboard',
            'applications/vibra-web/actividades',
            'applications/vibra-web/emociones',
            'applications/vibra-web/participantes',
            'applications/vibra-web/cursos',
            'applications/vibra-web/feedback',
            'applications/vibra-web/analytics',
            'applications/vibra-web/componentes',
          ],
        },
        {
          type: 'category',
          label: 'Vibra Mobile (App)',
          items: [
            'applications/vibra-mobile/actividad-diaria',
            'applications/vibra-mobile/retos',
            'applications/vibra-mobile/eventos-personales',
            'applications/vibra-mobile/perfil',
            'applications/vibra-mobile/offline',
            'applications/vibra-mobile/componentes',
          ],
        },
        {
          type: 'category',
          label: 'Base de Datos',
          items: [
            'applications/base-de-datos/modelo',
            'applications/base-de-datos/colecciones',
            'applications/base-de-datos/indices',
          ],
        },
      ],
    },

    // ── Desarrollo ──
    {
      type: 'category',
      label: 'Desarrollo',
      items: [
        'developed/plan-desarrollo',
        {
          type: 'category',
          label: 'Informes por fase',
          items: [
            'developed/fase4-integration-testing',
            'developed/fase4-performance',
            'developed/fase4-bugfixing',
            'developed/fase4-optimization',
          ],
        },
      ],
    },

    // ── Sponsors ──
    'applications/sponsors/sponsors',

    // ── Guías ──
    {
      type: 'category',
      label: 'Guías',
      items: [
        'guias/usuario-web',
        'guias/usuario-mobile',
        'guias/despliegue',
        'guias/desarrollo',
      ],
    },

    // ── API Reference ──
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/referencia-endpoints',
        {
          type: 'autogenerated',
          dirName: 'api/endpoints',
        },
      ],
    },

    // ── Changelog ──
    'changelog',

    // ── Técnico ──
    {
      type: 'category',
      label: 'Técnico',
      items: [
        'tecnico/rate-limiting',
        'tecnico/autenticacion',
      ],
    },
  ],
};

export default sidebars;
